spring:
  datasource:
    url: jdbc:mysql://rm-bp1g91f4t63f1h24h6o.mysql.rds.aliyuncs.com:3306/qs_cms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: lzzhuang
    password: 951116Lzz!
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.macro.mall: debug