server:
  port: 9201
spring:
  application:
    name: questions-gateway
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      # 跨域
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods:
              - GET
                POST
                DELETE
                PUT
                OPTION
      routes:
        - id: questions-study
          uri: lb://questions-study
          predicates:
            - Path=/questions-study/**
          filters:
            - StripPrefix=1
        - id: questions-question
          uri: lb://questions-question
          predicates:
            - Path=/questions-question/**
          filters:
            - StripPrefix=1
        - id: questions-admin
          uri: lb://questions-admin
          predicates:
            - Path=/question-admin/**
          filters:
            - StripPrefix=1
        - id: questions-member
          uri: lb://questions-member
          predicates:
            - Path=/question-member/**
          filters:
            - StripPrefix=1
        - id: questions-content
          uri: lb://questions-content
          predicates:
            - Path=/question-content/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写



